FROM docker.io/node:20 as installer

ENV YARN_NPM_REGISTRY_SERVER=https://registry.npmmirror.com

COPY api /code/api

# Javascript

WORKDIR /code/api/_build

ENV YARN_VERSION 3.6.1
ENV YARN_IGNORE_NODE 1

RUN yarn set version $YARN_VERSION

RUN yarn install

FROM registry.cn-hongkong.aliyuncs.com/merico/node:20.10.0

COPY --from=installer /code/api/_build /code/api/_build

WORKDIR /code/api/_build

