FROM registry.cn-hongkong.aliyuncs.com/merico/node:lts_base_v2

ENV YARN_NPM_REGISTRY_SERVER=https://registry.npmmirror.com

COPY api /code/api

# Javascript

WORKDIR /code/api/_build

RUN yarn install
