FROM registry.cn-hongkong.aliyuncs.com/merico/node:lts_base_v2

ENV YARN_NPM_REGISTRY_SERVER=https://registry.npmmirror.com

COPY api /code/api

# Javascript

WORKDIR /code/api/_build

ENV YARN_VERSION 3.6.1

RUN yarn set version $YARN_VERSION

RUN yarn install
